name: weather
description: Flutter Weather App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_core: ^1.15.0
  firebase_remote_config: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0
  geolocator: ^8.2.1
  get_it: ^7.2.0
  go_router: ^3.0.7
  google_fonts: ^3.0.1
  injectable: ^1.5.2
  intl: ^0.17.0
  json_annotation: ^4.5.0
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.0.1+1

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  fake_firebase_remote_config: ^1.0.2
  flutter_gen_runner: ^4.1.6
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.5
  mocktail: ^0.2.0
  retrofit_generator: ^3.0.1
  very_good_analysis: ^2.4.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/google_fonts/
