// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8dDmCoGatP4C0a1_cABqH-MEgG537GgE',
    appId: '1:1076366540919:web:5cd3b46f15f5a64fbb0672',
    messagingSenderId: '1076366540919',
    projectId: 'flutter-weather-production',
    authDomain: 'flutter-weather-production.firebaseapp.com',
    storageBucket: 'flutter-weather-production.appspot.com',
    measurementId: 'G-2873F5HB3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeGAiYbk_SrfD8Q3G9OVQW9AQ6TTnT3Gs',
    appId: '1:1076366540919:android:ce12d8dd297d6bb6bb0672',
    messagingSenderId: '1076366540919',
    projectId: 'flutter-weather-production',
    storageBucket: 'flutter-weather-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGg_RUcf_RNqWNJ-ZbG-s3Z4WBTqCGaks',
    appId: '1:1076366540919:ios:c5177f9d5377e7b6bb0672',
    messagingSenderId: '1076366540919',
    projectId: 'flutter-weather-production',
    storageBucket: 'flutter-weather-production.appspot.com',
    iosClientId: '1076366540919-ovh3ge8ouit74vb63q5jguqqh65erhi1.apps.googleusercontent.com',
    iosBundleId: 'dev.adryanev.weather',
  );
}
