name: weather

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 2.10.0
      min_coverage: 75
      coverage_excludes: "*.g.dart *.freezed.dart *.config.dart"
